version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agoda_postgres_db
    restart: always
    environment:
      POSTGRES_USER: agoda_admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: agoda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
